services:
  message-crypter:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SECRET_WEB_KEY: <mywebkey>
      DATABASE_URL: <mydbfile.db>
      SECRET_FILE_KEY: <mysecretkey.key>
      BASE_URL: <http://127.0.0.1:5000/>
    restart: unless-stopped