CREATE TABLE myDatabase.Links (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lien VARCHAR(8) UNIQUE NOT NULL,
    texte VARBINARY(150) NOT NULL,
    salt VARBINARY(16) NOT NULL,
    usesLink BOOLEAN NOT NULL
);
